#! /bin/bash

set -euo pipefail

##
#/
#/ Executes v-mount with the passed arguments and opens a shell with the mounted directory
#/
##

where_am_i="${0%/*}"
source "${where_am_i}/tools/common"

cleanup() {
  trap '' EXIT INT QUIT ABRT TERM
  [[ -z "${pipe_path}" ]] ||
    rm "${pipe_path}"

  [[ -z "${vmount_pid}" ]] || {
    while kill -0 ${vmount_pid} 2>/dev/null; do
      kill ${vmount_pid} 2>/dev/null
      sleep 1
    done
  }
  exit "${1}"
}

vmount_pid=0
pipe_path=""
trap 'cleanup $?' EXIT INT QUIT ABRT TERM

pipe_path=$(mktemp -u)
mkfifo "${pipe_path}"
exec 3<>"${pipe_path}"

v-mount "$@" &
vmount_pid=$!

started_or_error="$(head -n1 <&3)"
[[ "${started_or_error}" = "STARTED" ]] ||
  die "Failed to execute v-mount."

mount_point="$(head -n1 <&3)"
"${where_am_i}"/tools/exec-shell -C "${mount_point}"
